In [214]:
import tensorflow as tf
from tensorflow.contrib import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import pandas_datareader.data as web
import talib as ta
from sklearn.preprocessing import MinMaxScaler

In [35]:
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2017, 5, 31)
gspc2 = web.DataReader("^GSPC", 'yahoo', start, end)
gspc2.rename(columns={'Adj Close' :'Adj_Close'}, inplace=True)
gspc2['pct_change'] = gspc2['Adj_Close'].pct_change()

gspc2['pct_change_lag1'] = gspc2['pct_change'].shift(1)


gspc2['pct_change_lag2'] = gspc2['Adj_Close'].pct_change(2)
gspc2['pct_change_lag3'] = gspc2['Adj_Close'].pct_change(3)
gspc2['pct_change_lag4'] = gspc2['Adj_Close'].pct_change(4)
gspc2['pct_change_lag5'] = gspc2['Adj_Close'].pct_change(5)
gspc2['pct_change_lag6'] = gspc2['Adj_Close'].pct_change(6)
gspc2['pct_change_lag7'] = gspc2['Adj_Close'].pct_change(7)
gspc2['pct_change_lag8'] = gspc2['Adj_Close'].pct_change(8)

gspc2['pct_change_lag2'] = gspc2['pct_change_lag2'].shift(1)
gspc2['pct_change_lag3'] = gspc2['pct_change_lag3'].shift(1)
gspc2['pct_change_lag4'] = gspc2['pct_change_lag4'].shift(1)
gspc2['pct_change_lag5'] = gspc2['pct_change_lag5'].shift(1)
gspc2['pct_change_lag6'] = gspc2['pct_change_lag6'].shift(1)
gspc2['pct_change_lag7'] = gspc2['pct_change_lag7'].shift(1)
gspc2['pct_change_lag8'] = gspc2['pct_change_lag8'].shift(1)


gspc2['day_lag1'] = gspc2['pct_change'].shift(1)
gspc2['day_lag2'] = gspc2['pct_change'].shift(2)
gspc2['day_lag3'] = gspc2['pct_change'].shift(3)
gspc2['day_lag4'] = gspc2['pct_change'].shift(4)
gspc2['day_lag5'] = gspc2['pct_change'].shift(5)
gspc2['day_lag6'] = gspc2['pct_change'].shift(6)
gspc2['day_lag7'] = gspc2['pct_change'].shift(7)
gspc2['day_lag8'] = gspc2['pct_change'].shift(8)
# gspc2['pct_change1'] = gspc2['Adj_Close'].shift(-1) / gspc2['Adj_Close']  - 1
# gspc2['pct_change2'] = gspc2['Adj_Close'].shift(-2) / gspc2['Adj_Close']  - 1
# gspc2['pct_change3'] = gspc2['Adj_Close'].shift(-3) / gspc2['Adj_Close']  - 1
# gspc2['pct_change4'] = gspc2['Adj_Close'].shift(-4) / gspc2['Adj_Close']  - 1
# gspc2['pct_change5'] = gspc2['Adj_Close'].shift(-5) / gspc2['Adj_Close']  - 1
# gspc2['pct_change6'] = gspc2['Adj_Close'].shift(-6) / gspc2['Adj_Close']  - 1
# gspc2['pct_change7'] = gspc2['Adj_Close'].shift(-7) / gspc2['Adj_Close']  - 1
# gspc2['pct_change8'] = gspc2['Adj_Close'].shift(-8) / gspc2['Adj_Close']  - 1

# gspc2 = gspc2.ix[(gspc2['pct_change'] > 0.0200)]
gspc2['lr3_10'], gspc2['lr3_10signal'], gspc2['hist'] = ta.MACDEXT(gspc2.Adj_Close.values, fastperiod=3, fastmatype=0, slowperiod=10, slowmatype=0, signalperiod=16, signalmatype=0)
gspc2['lr3_10_lag1'] = gspc2.lr3_10.shift(1)
gspc2['lr3_10_lag2'] = gspc2.lr3_10.shift(2)
gspc2['lr3_10_lag3'] = gspc2.lr3_10.shift(3)
gspc2['lr3_10_lag4'] = gspc2.lr3_10.shift(4)
gspc2['lr3_10_lag5'] = gspc2.lr3_10.shift(5)
gspc2['lr3_10signal_lag1'] = gspc2.lr3_10signal.shift(1)
gspc2['lr3_10signal_lag2'] = gspc2.lr3_10signal.shift(2)
gspc2['lr3_10signal_lag3'] = gspc2.lr3_10signal.shift(3)
gspc2['lr3_10signal_lag4'] = gspc2.lr3_10signal.shift(4)
gspc2['lr3_10signal_lag5'] = gspc2.lr3_10signal.shift(5)
gspc2['hist_lag1'] = gspc2['hist'].shift(1)
gspc2['hist_lag2'] = gspc2['hist'].shift(2)
gspc2['hist_lag3'] = gspc2['hist'].shift(3)
gspc2['hist_lag4'] = gspc2['hist'].shift(4)
gspc2['hist_lag5'] = gspc2['hist'].shift(5)
gspc2['rsi14'] = ta.RSI(gspc2.Adj_Close.values, timeperiod=14)
gspc2['rsi14_lag1'] = gspc2.rsi14.shift(1)
gspc2['rsi14_lag2'] = gspc2.rsi14.shift(2)
gspc2['rsi14_lag3'] = gspc2.rsi14.shift(3)
gspc2['rsi14_lag4'] = gspc2.rsi14.shift(4)
gspc2['rsi14_lag5'] = gspc2.rsi14.shift(5)
# gspc2['upperband'], gspc2['middleband'], gspc2['lowerband'] = ta.BBANDS(gspc2.Adj_Close.values, timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)
# # BB crossed down and up categorical labels
# gspc2.ix[(gspc2['Adj_Close'] <= gspc2['lowerband']) , 'crossed_down'] = 1
# gspc2.ix[(gspc2['Adj_Close'] > gspc2['lowerband']) , 'crossed_down'] = 0
# gspc2.ix[(gspc2['Adj_Close'] >= gspc2['upperband']) , 'crossed_up'] = 1
# gspc2.ix[(gspc2['Adj_Close'] < gspc2['upperband']) , 'crossed_up'] = 0
gspc2['mama'], gspc2['fama'] = ta.MAMA(gspc2.Adj_Close.values, fastlimit=0.5, slowlimit=0.05)
gspc2['hilbert'] = ta.HT_TRENDLINE(gspc2.Adj_Close.values)
gspc2['atr'] = ta.ATR(gspc2.High.values, gspc2.Low.values, gspc2.Close.values, timeperiod=14)
gspc2.ix[gspc2['pct_change'] >= 0, 'direction'] = 1
gspc2.ix[gspc2['pct_change'] < 0, 'direction'] = 0
gspc2['direction_lag1'] = gspc2['direction'].shift(1)
gspc2['direction_lag2'] = gspc2['direction'].shift(2)
gspc2['direction_lag3'] = gspc2['direction'].shift(3)
gspc2['direction_lag4'] = gspc2['direction'].shift(4)
gspc2['direction_lag5'] = gspc2['direction'].shift(5)
gspc2['direction_lag6'] = gspc2['direction'].shift(6)
gspc2['direction_lag7'] = gspc2['direction'].shift(7)
gspc2['direction_lag8'] = gspc2['direction'].shift(8)

# gspc2.ix[gspc2['pct_change2'] >= 0, 'pct_change2_yn'] = 1
# gspc2.ix[gspc2['pct_change2'] < 0, 'pct_change2_yn'] = 0
# gspc2.ix[gspc2['pct_change3'] >= 0, 'pct_change3_yn'] = 1
# gspc2.ix[gspc2['pct_change3'] < 0, 'pct_change3_yn'] = 0
# gspc2.ix[gspc2['pct_change4'] >= 0, 'pct_change4_yn'] = 1
# gspc2.ix[gspc2['pct_change4'] < 0, 'pct_change4_yn'] = 0
# gspc2.ix[gspc2['pct_change5'] >= 0, 'pct_change5_yn'] = 1
# gspc2.ix[gspc2['pct_change5'] < 0, 'pct_change5_yn'] = 0
# gspc2.ix[gspc2['pct_change6'] >= 0, 'pct_change6_yn'] = 1
# gspc2.ix[gspc2['pct_change6'] < 0, 'pct_change6_yn'] = 0
# gspc2.ix[gspc2['pct_change7'] >= 0, 'pct_change7_yn'] = 1
# gspc2.ix[gspc2['pct_change7'] < 0, 'pct_change7_yn'] = 0

gspc2.head(20)
gspc2.dropna(axis=0,inplace=True)
# gspc2[pd.isnull(gspc2).any(axis=1)]
gspc2['High_shift2'] = gspc2.High.shift(2)
gspc2['Low_shift2'] = gspc2.Low.shift(2)
gspc2['Close_shift2'] = gspc2.Close.shift(2)
gspc2['Open_dev_close_shift2'] = gspc2.Open / gspc2.Close_shift2
gspc2['High_dev_close_shift2'] = gspc2.Open / gspc2.High_shift2
gspc2['Low_dev_close_shift2'] = gspc2.Open / gspc2.Low_shift2
gspc2.dropna(axis=0,inplace=True)
gspc3 = gspc2[[ 'Open', 'Volume' , 'direction_lag1', 'direction_lag2','lr3_10_lag1', 'lr3_10_lag2', 'lr3_10_lag3', \
               'direction', 'High_shift2', 'Low_shift2', 'Close_shift2', 'Open_dev_close_shift2', \
               'High_dev_close_shift2',
       'Low_dev_close_shift2']]

In [40]:
gspc4 = round(gspc2.ix[:,['Adj_Close', 'pct_change', 'direction']],4)
gspc4.tail(10)
gspc4.shape


(1783, 3)

In [68]:
gspc4["pct_change"].values[-20:-1]


array([-0.0008,  0.0007, -0.0014, -0.0038, -0.0068,  0.0086, -0.0029,
       -0.0017,  0.0076, -0.003 ,  0.0108,  0.0061, -0.0005,  0.0006,
       -0.0019,  0.0017,  0.0012, -0.0013,  0.0006])

In [272]:

seq_length = 5

dataX = []
dataY = []
for i in range(0, len(gspc4["pct_change"].values) - seq_length, 1):
    seq_in = gspc4["pct_change"].values[i:i + seq_length]
    scaler = MinMaxScaler(feature_range=(-1, 1))
    seq_in = scaler.fit_transform(seq_in)

    seq_out = gspc4["pct_change"].values[i + seq_length]
    dataX.append([char for char in seq_in])
    dataY.append([seq_out])
    print(seq_in, '->', seq_out)

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

[-0.48571429  0.14285714 -0.79047619 -1.          1.        ] -> 0.0008
[ 0.14285714 -0.79047619 -1.          1.         -0.98095238] -> -0.0161
[ 0.31135531  0.23076923  1.          0.23809524 -1.        ] -> 0.0045
[ 0.23076923  1.          0.23809524 -1.          0.50915751] -> 0.0081
[ 1.          0.23809524 -1.          0.50915751  0.77289377] -> -0.001
[ 0.39669421 -1.          0.70247934  1.          0.24793388] -> 0.0023
[-1.          0.70247934  1.          0.24793388  0.52066116] -> 0.0071
[ 0.20879121  1.         -1.         -0.27472527  0.78021978] -> -0.0043
[ 1.         -0.46774194  0.06451613  0.83870968 -1.        ] -> -0.0234
[ 0.46885246  0.6852459   1.          0.25245902 -1.        ] -> 0.0065
[ 0.6852459   1.          0.25245902 -1.          0.96065574] -> 0.0129
[ 0.68044077  0.0523416  -1.          0.64738292  1.        ] -> -0.0166
[ 0.0523416  -1.          0.64738292  1.         -0.62534435] -> 0.0131
[-1.          0.63835616  0.9890411  -0.62739726  1.        

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

 -> -0.0118
[ 0.19753086 -0.54320988  1.         -0.0617284  -1.        ] -> -0.0012
[-0.54320988  1.         -0.0617284  -1.          0.30864198] -> -0.0162
[ 1.          0.16504854 -0.57281553  0.45631068 -1.        ] -> 0.0002
[ 0.46341463 -0.46341463  0.82926829 -1.          1.        ] -> 0.0154
[-0.72151899 -0.05063291 -1.          0.03797468  1.        ] -> 0.0025
[-0.05063291 -1.          0.03797468  1.          0.1835443 ] -> -0.0016
[-1.          0.03797468  1.          0.1835443  -0.07594937] -> -0.0143
[-0.02356902  1.          0.13131313 -0.14478114 -1.        ] -> 0.0149
[ 1.          0.13131313 -0.14478114 -1.          0.96632997] -> -0.0075
[ 0.15068493 -0.13013699 -1.          1.         -0.53424658] -> -0.0014
[-0.13013699 -1.          1.         -0.53424658 -0.11643836] -> -0.0061
[-1.          1.         -0.53424658 -0.11643836 -0.43835616] -> 0.0216
[ 0.5395189  -1.         -0.58075601 -0.90378007  1.        ] -> 0.0128
[-1.         -0.58075601 -0.90378007  1.     

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you


[ 0.22167488 -0.14285714 -0.05418719  1.         -1.        ] -> 0.0022
[-0.14285714 -0.05418719  1.         -1.          0.14285714] -> 0.0079
[-0.05418719  1.         -1.          0.14285714  0.7044335 ] -> -0.0237
[ 1.         -0.1734104   0.49710983  0.8265896  -1.        ] -> -0.0122
[-0.09493671  0.63924051  1.         -1.         -0.2721519 ] -> 0.0017
[ 0.63924051  1.         -1.         -0.2721519   0.60759494] -> 0.0001
[ 1.         -1.         -0.2721519   0.60759494  0.50632911] -> -0.004
[-1.         -0.09448819  1.          0.87401575  0.5511811 ] -> -0.0139
[-0.78205128  1.          0.79487179  0.26923077 -1.        ] -> -0.0016
[ 1.          0.79487179  0.26923077 -1.          0.57692308] -> 0.0048
[ 0.4973262   0.05882353 -1.          0.31550802  1.        ] -> 0.0199
[-0.41420118 -1.         -0.27218935  0.10650888  1.        ] -> 0.0007
[-1.         -0.27218935  0.10650888  1.         -0.13609467] -> 0.0023
[-1.         -0.40465116  1.         -0.78604651 -0.6372093

[-0.44751381 -1.          1.         -0.0718232   0.83425414] -> 0.0129
[-1.          0.23129252 -0.42857143  0.1292517   1.        ] -> 0.0091
[-0.07619048 -1.         -0.21904762  1.          0.63809524] -> 0.0196
[-1.         -0.40794224  0.51624549  0.24187726  1.        ] -> -0.0073
[-0.44981413  0.50185874  0.21933086  1.         -1.        ] -> 0.0123
[ 0.50185874  0.21933086  1.         -1.          0.45724907] -> 0.0071
[ 0.21933086  1.         -1.          0.45724907  0.07063197] -> -0.0015
[ 1.         -1.          0.45724907  0.07063197 -0.56877323] -> 0.0119
[-1.          1.          0.46938776 -0.40816327  0.95918367] -> -0.0014
[ 1.          0.24637681 -1.          0.94202899 -0.98550725] -> 0.0062
[ 0.28358209 -1.          1.         -0.98507463  0.14925373] -> 0.0117
[-1.          1.         -0.98507463  0.14925373  0.97014925] -> -0.0001
[ 1.         -1.          0.14285714  0.96992481 -0.80451128] -> -0.0028
[-0.80689655  0.24137931  1.         -0.62758621 -1.       

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

In [273]:
X = np.reshape(dataX, (len(dataX), seq_length, 1))
# X = X / float(len(gspc4["pct_change"].values))
len(dataY)

# dataY conveeted into binary classification 1.0 and 0.0
dataYseries = pd.DataFrame(dataY)
dataYseries.ix[dataYseries[0] >= 0, ] = 1
dataYseries.ix[dataYseries[0] < 0, ] = 0
X[:20]

array([[[-0.48571429],
        [ 0.14285714],
        [-0.79047619],
        [-1.        ],
        [ 1.        ]],

       [[ 0.14285714],
        [-0.79047619],
        [-1.        ],
        [ 1.        ],
        [-0.98095238]],

       [[ 0.31135531],
        [ 0.23076923],
        [ 1.        ],
        [ 0.23809524],
        [-1.        ]],

       [[ 0.23076923],
        [ 1.        ],
        [ 0.23809524],
        [-1.        ],
        [ 0.50915751]],

       [[ 1.        ],
        [ 0.23809524],
        [-1.        ],
        [ 0.50915751],
        [ 0.77289377]],

       [[ 0.39669421],
        [-1.        ],
        [ 0.70247934],
        [ 1.        ],
        [ 0.24793388]],

       [[-1.        ],
        [ 0.70247934],
        [ 1.        ],
        [ 0.24793388],
        [ 0.52066116]],

       [[ 0.20879121],
        [ 1.        ],
        [-1.        ],
        [-0.27472527],
        [ 0.78021978]],

       [[ 1.        ],
        [-0.46774194],
        [ 0.064516

In [274]:
# moving dataYseries to on-hot-encoder
y = keras.utils.to_categorical(dataYseries)
y

array([[ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       ..., 
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.]])

## Very important - data needs to be normalized in format [-1, 1] for LSTM
## After this change the results in training accuracy went drastically up

In [275]:
"""
stateful = False
"""
# create and fit the model
batch_size = X.shape[0]
model = keras.models.Sequential()
model.add(keras.layers.LSTM(128, input_shape=(X.shape[1], X.shape[2])))
model.add(keras.layers.Dense(y.shape[1], activation='softmax'))
adam = keras.optimizers.Adam(lr=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
model.fit(X, y, epochs=600, batch_size=batch_size, verbose=1, shuffle=False)

# seq_length = 4
# max accuracy = 0.5419 normalized 0 to 1 with all sorts of lr= [0.0001, 0.001, 0.01]
# max accuracy 0.5492 with normalized between -1 and 1, lr= 0.01
# neur = 3, epochs=200, bs = 1, norm [-1, 1], lr=0.05, acc 0.58
# neur = 3, epochs=200, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.58
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.59
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.04 --  acc = 0.584
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.06 --  acc = 0.5953
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.07 --  acc = 0.5953
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.08 --  acc = 0.5975
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.1 --  acc = 0.5840
# neur = 16, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.747
# neur = 32, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.81
# neur = 64, epochs=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.85
# neur = 128, epochs=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.92
# seq = 5, neur = 128, epochs=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0

Epoch 1/600
1778/1778 [==============================] - 3s - loss: 0.6930 - acc: 0.5079
Epoch 2/600
1778/1778 [==============================] - 0s - loss: 0.7527 - acc: 0.5366
Epoch 3/600
1778/1778 [==============================] - 0s - loss: 0.6964 - acc: 0.5062
Epoch 4/600
1778/1778 [==============================] - 0s - loss: 0.7013 - acc: 0.5416
Epoch 5/600
1778/1778 [==============================] - 0s - loss: 0.6910 - acc: 0.5416
Epoch 6/600
1778/1778 [==============================] - 0s - loss: 0.7005 - acc: 0.5416
Epoch 7/600
1778/1778 [==============================] - 0s - loss: 0.7004 - acc: 0.4741
Epoch 8/600
1778/1778 [==============================] - 0s - loss: 0.6897 - acc: 0.5427
Epoch 9/600
1778/1778 [==============================] - 0s - loss: 0.6991 - acc: 0.5416
Epoch 10/600
1778/1778 [==============================] - 0s - loss: 0.6993 - acc: 0.4848
Epoch 11/600
1778/1778 [==============================] - 0s - loss: 0.6898 - acc: 0.5416
Epoch 12/600
1778/1

1778/1778 [==============================] - 0s - loss: 0.6313 - acc: 0.6434
Epoch 93/600
1778/1778 [==============================] - 0s - loss: 0.6344 - acc: 0.6299
Epoch 94/600
1778/1778 [==============================] - 0s - loss: 0.6291 - acc: 0.6204
Epoch 95/600
1778/1778 [==============================] - 0s - loss: 0.6128 - acc: 0.6524
Epoch 96/600
1778/1778 [==============================] - 0s - loss: 0.6156 - acc: 0.6395
Epoch 97/600
1778/1778 [==============================] - 0s - loss: 0.5999 - acc: 0.6755
Epoch 98/600
1778/1778 [==============================] - 0s - loss: 0.6013 - acc: 0.6603
Epoch 99/600
1778/1778 [==============================] - 0s - loss: 0.5966 - acc: 0.6597
Epoch 100/600
1778/1778 [==============================] - 0s - loss: 0.5878 - acc: 0.6828
Epoch 101/600
1778/1778 [==============================] - 0s - loss: 0.5957 - acc: 0.6659
Epoch 102/600
1778/1778 [==============================] - 0s - loss: 0.5964 - acc: 0.6659
Epoch 103/600
1778/1

1778/1778 [==============================] - 0s - loss: 0.1943 - acc: 0.9134
Epoch 183/600
1778/1778 [==============================] - 0s - loss: 0.2076 - acc: 0.9044
Epoch 184/600
1778/1778 [==============================] - 0s - loss: 0.2370 - acc: 0.8988
Epoch 185/600
1778/1778 [==============================] - 0s - loss: 0.2066 - acc: 0.9055
Epoch 186/600
1778/1778 [==============================] - 0s - loss: 0.1757 - acc: 0.9258
Epoch 187/600
1778/1778 [==============================] - 0s - loss: 0.1961 - acc: 0.9134
Epoch 188/600
1778/1778 [==============================] - 0s - loss: 0.1857 - acc: 0.9139
Epoch 189/600
1778/1778 [==============================] - 0s - loss: 0.1697 - acc: 0.9190
Epoch 190/600
1778/1778 [==============================] - 0s - loss: 0.1871 - acc: 0.9139
Epoch 191/600
1778/1778 [==============================] - 0s - loss: 0.1719 - acc: 0.9280
Epoch 192/600
1778/1778 [==============================] - 0s - loss: 0.1750 - acc: 0.9241
Epoch 193/600

1778/1778 [==============================] - 0s - loss: 0.1032 - acc: 0.9601
Epoch 273/600
1778/1778 [==============================] - 0s - loss: 0.0967 - acc: 0.9612
Epoch 274/600
1778/1778 [==============================] - 0s - loss: 0.0915 - acc: 0.9629
Epoch 275/600
1778/1778 [==============================] - 0s - loss: 0.0900 - acc: 0.9702
Epoch 276/600
1778/1778 [==============================] - 0s - loss: 0.0920 - acc: 0.9668
Epoch 277/600
1778/1778 [==============================] - 0s - loss: 0.0906 - acc: 0.9674
Epoch 278/600
1778/1778 [==============================] - 0s - loss: 0.0804 - acc: 0.9741
Epoch 279/600
1778/1778 [==============================] - 0s - loss: 0.0831 - acc: 0.9730
Epoch 280/600
1778/1778 [==============================] - 0s - loss: 0.0861 - acc: 0.9663
Epoch 281/600
1778/1778 [==============================] - 0s - loss: 0.0853 - acc: 0.9663
Epoch 282/600
1778/1778 [==============================] - 0s - loss: 0.0860 - acc: 0.9674
Epoch 283/600

1778/1778 [==============================] - 0s - loss: 0.1519 - acc: 0.9404
Epoch 363/600
1778/1778 [==============================] - 0s - loss: 0.1653 - acc: 0.9173
Epoch 364/600
1778/1778 [==============================] - 0s - loss: 0.1394 - acc: 0.9336
Epoch 365/600
1778/1778 [==============================] - 0s - loss: 0.1273 - acc: 0.9550
Epoch 366/600
1778/1778 [==============================] - 0s - loss: 0.1259 - acc: 0.9499
Epoch 367/600
1778/1778 [==============================] - 0s - loss: 0.1199 - acc: 0.9522
Epoch 368/600
1778/1778 [==============================] - 0s - loss: 0.1114 - acc: 0.9634
Epoch 369/600
1778/1778 [==============================] - 0s - loss: 0.1085 - acc: 0.9578
Epoch 370/600
1778/1778 [==============================] - 0s - loss: 0.1026 - acc: 0.9618
Epoch 371/600
1778/1778 [==============================] - 0s - loss: 0.0963 - acc: 0.9668
Epoch 372/600
1778/1778 [==============================] - 0s - loss: 0.0913 - acc: 0.9691
Epoch 373/600

1778/1778 [==============================] - 0s - loss: 0.0238 - acc: 0.9955
Epoch 453/600
1778/1778 [==============================] - 0s - loss: 0.0324 - acc: 0.9938
Epoch 454/600
1778/1778 [==============================] - 0s - loss: 0.0378 - acc: 0.9865
Epoch 455/600
1778/1778 [==============================] - 0s - loss: 0.0579 - acc: 0.9814
Epoch 456/600
1778/1778 [==============================] - 0s - loss: 0.0412 - acc: 0.9871
Epoch 457/600
1778/1778 [==============================] - 0s - loss: 0.0464 - acc: 0.9826
Epoch 458/600
1778/1778 [==============================] - 0s - loss: 0.0706 - acc: 0.9769
Epoch 459/600
1778/1778 [==============================] - 0s - loss: 0.0513 - acc: 0.9826
Epoch 460/600
1778/1778 [==============================] - 0s - loss: 0.0700 - acc: 0.9741
Epoch 461/600
1778/1778 [==============================] - 0s - loss: 0.0444 - acc: 0.9814
Epoch 462/600
1778/1778 [==============================] - 0s - loss: 0.0391 - acc: 0.9871
Epoch 463/600

1778/1778 [==============================] - 0s - loss: 0.0105 - acc: 0.9994
Epoch 543/600
1778/1778 [==============================] - 0s - loss: 0.0103 - acc: 0.9994
Epoch 544/600
1778/1778 [==============================] - 0s - loss: 0.0101 - acc: 0.9994
Epoch 545/600
1778/1778 [==============================] - 0s - loss: 0.0099 - acc: 0.9994
Epoch 546/600
1778/1778 [==============================] - 0s - loss: 0.0098 - acc: 0.9994
Epoch 547/600
1778/1778 [==============================] - 0s - loss: 0.0097 - acc: 1.0000
Epoch 548/600
1778/1778 [==============================] - 0s - loss: 0.0095 - acc: 0.9994
Epoch 549/600
1778/1778 [==============================] - 0s - loss: 0.0093 - acc: 0.9994
Epoch 550/600
1778/1778 [==============================] - 0s - loss: 0.0092 - acc: 1.0000
Epoch 551/600
1778/1778 [==============================] - 0s - loss: 0.0090 - acc: 1.0000
Epoch 552/600
1778/1778 [==============================] - 0s - loss: 0.0089 - acc: 1.0000
Epoch 553/600

In [279]:
"""
stateful = True
"""
# create and fit the model
batch_size = X.shape[0]
model = keras.models.Sequential()
model.add(keras.layers.LSTM(16, batch_input_shape=(batch_size, X.shape[1], X.shape[2]), stateful=True))
model.add(keras.layers.Dense(y.shape[1], activation='softmax'))
adam = keras.optimizers.Adam(lr=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
for i in range(600):
	model.fit(X, y, epochs=1, batch_size=batch_size, verbose=2, shuffle=False)
	model.reset_states()
# summarize performance of the model
scores = model.evaluate(X, y, batch_size=batch_size, verbose=0)
model.reset_states()
print("Model Accuracy: %.2f%%" % (scores[1]*100))

# the same accuracy as in stateful=False  = 0.5419 !! with input data being normalized between 0 and 1
# after changing it to be between -1 and 1 , accuracy went up to 0.5554
# after increasing lr from 0.01 to 0.05, accuracy = 0.73
# seq = 4, neur = 32, epo=300, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.856
# seq = 4, neur = 64, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.87
# seq = 4, neur = 128, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.946
# seq = 4, neur = 256, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.648
# seq = 4, neur = 128, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.616
# seq = 5, neur = 128, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0
# seq = 5, neur = 64, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0
# seq = 5, neur = 32, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0
# seq = 5, neur = 16, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.90

Epoch 1/1
3s - loss: 0.6929 - acc: 0.5006
Epoch 1/1
0s - loss: 0.6935 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6896 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6904 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6901 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6894 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6894 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6897 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6895 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6891 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6888 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6888 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6887 - acc: 0.5416
Epoch 1/1
0s - loss: 0.6884 - acc: 0.5411
Epoch 1/1
0s - loss: 0.6880 - acc: 0.5467
Epoch 1/1
0s - loss: 0.6878 - acc: 0.5422
Epoch 1/1
0s - loss: 0.6877 - acc: 0.5444
Epoch 1/1
0s - loss: 0.6877 - acc: 0.5411
Epoch 1/1
0s - loss: 0.6875 - acc: 0.5517
Epoch 1/1
0s - loss: 0.6873 - acc: 0.5489
Epoch 1/1
0s - loss: 0.6871 - acc: 0.5495
Epoch 1/1
0s - loss: 0.6870 - acc: 0.5450
Epoch 1/1
0s - loss: 0.6868 - acc: 0.5456
Epoch 1/1
0s - loss: 0.6864 - acc:

0s - loss: 0.3091 - acc: 0.8633
Epoch 1/1
0s - loss: 0.3044 - acc: 0.8628
Epoch 1/1
0s - loss: 0.3073 - acc: 0.8667
Epoch 1/1
0s - loss: 0.3103 - acc: 0.8566
Epoch 1/1
0s - loss: 0.2982 - acc: 0.8678
Epoch 1/1
0s - loss: 0.2901 - acc: 0.8729
Epoch 1/1
0s - loss: 0.2965 - acc: 0.8673
Epoch 1/1
0s - loss: 0.2883 - acc: 0.8774
Epoch 1/1
0s - loss: 0.2912 - acc: 0.8780
Epoch 1/1
0s - loss: 0.2919 - acc: 0.8729
Epoch 1/1
0s - loss: 0.2927 - acc: 0.8735
Epoch 1/1
0s - loss: 0.2906 - acc: 0.8735
Epoch 1/1
0s - loss: 0.2769 - acc: 0.8819
Epoch 1/1
0s - loss: 0.2784 - acc: 0.8813
Epoch 1/1
0s - loss: 0.2790 - acc: 0.8791
Epoch 1/1
0s - loss: 0.2792 - acc: 0.8796
Epoch 1/1
0s - loss: 0.2721 - acc: 0.8830
Epoch 1/1
0s - loss: 0.2709 - acc: 0.8903
Epoch 1/1
0s - loss: 0.2713 - acc: 0.8892
Epoch 1/1
0s - loss: 0.2676 - acc: 0.8847
Epoch 1/1
0s - loss: 0.2640 - acc: 0.8954
Epoch 1/1
0s - loss: 0.2642 - acc: 0.8920
Epoch 1/1
0s - loss: 0.2625 - acc: 0.8931
Epoch 1/1
0s - loss: 0.2571 - acc: 0.8943
Ep

0s - loss: 0.1326 - acc: 0.9640
Epoch 1/1
0s - loss: 0.1424 - acc: 0.9550
Epoch 1/1
0s - loss: 0.1554 - acc: 0.9483
Epoch 1/1
0s - loss: 0.2370 - acc: 0.9145
Epoch 1/1
0s - loss: 0.2437 - acc: 0.9016
Epoch 1/1
0s - loss: 0.2515 - acc: 0.8999
Epoch 1/1
0s - loss: 0.2550 - acc: 0.9055
Epoch 1/1
0s - loss: 0.3363 - acc: 0.8650
Epoch 1/1
0s - loss: 0.1971 - acc: 0.9274
Epoch 1/1
0s - loss: 0.2620 - acc: 0.8864
Epoch 1/1
0s - loss: 0.2712 - acc: 0.8898
Epoch 1/1
0s - loss: 0.2325 - acc: 0.9049
Epoch 1/1
0s - loss: 0.2958 - acc: 0.8841
Epoch 1/1
0s - loss: 0.2103 - acc: 0.9117
Epoch 1/1
0s - loss: 0.2803 - acc: 0.8808
Epoch 1/1
0s - loss: 0.2166 - acc: 0.9168
Epoch 1/1
0s - loss: 0.2270 - acc: 0.9072
Epoch 1/1
0s - loss: 0.1986 - acc: 0.9139
Epoch 1/1
0s - loss: 0.2181 - acc: 0.9100
Epoch 1/1
0s - loss: 0.1835 - acc: 0.9168
Epoch 1/1
0s - loss: 0.1925 - acc: 0.9224
Epoch 1/1
0s - loss: 0.1757 - acc: 0.9348
Epoch 1/1
0s - loss: 0.1783 - acc: 0.9297
Epoch 1/1
0s - loss: 0.1666 - acc: 0.9359
Ep

Model Accuracy: 90.89%
