In [214]:
import tensorflow as tf
from tensorflow.contrib import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import pandas_datareader.data as web
import talib as ta
from sklearn.preprocessing import MinMaxScaler

In [360]:
start = datetime.datetime(2009, 7, 15)
end = datetime.datetime(2017, 5, 31)
gspc2 = web.DataReader("^GSPC", 'yahoo', start, end)
gspc2.rename(columns={'Adj Close' :'Adj_Close'}, inplace=True)
gspc2['pct_change'] = gspc2['Adj_Close'].pct_change()

gspc2['pct_change_lag1'] = gspc2['pct_change'].shift(1)


gspc2['pct_change_lag2'] = gspc2['Adj_Close'].pct_change(2)
gspc2['pct_change_lag3'] = gspc2['Adj_Close'].pct_change(3)
gspc2['pct_change_lag4'] = gspc2['Adj_Close'].pct_change(4)
gspc2['pct_change_lag5'] = gspc2['Adj_Close'].pct_change(5)
gspc2['pct_change_lag6'] = gspc2['Adj_Close'].pct_change(6)
gspc2['pct_change_lag7'] = gspc2['Adj_Close'].pct_change(7)
gspc2['pct_change_lag8'] = gspc2['Adj_Close'].pct_change(8)

gspc2['pct_change_lag2'] = gspc2['pct_change_lag2'].shift(1)
gspc2['pct_change_lag3'] = gspc2['pct_change_lag3'].shift(1)
gspc2['pct_change_lag4'] = gspc2['pct_change_lag4'].shift(1)
gspc2['pct_change_lag5'] = gspc2['pct_change_lag5'].shift(1)
gspc2['pct_change_lag6'] = gspc2['pct_change_lag6'].shift(1)
gspc2['pct_change_lag7'] = gspc2['pct_change_lag7'].shift(1)
gspc2['pct_change_lag8'] = gspc2['pct_change_lag8'].shift(1)


gspc2['day_lag1'] = gspc2['pct_change'].shift(1)
gspc2['day_lag2'] = gspc2['pct_change'].shift(2)
gspc2['day_lag3'] = gspc2['pct_change'].shift(3)
gspc2['day_lag4'] = gspc2['pct_change'].shift(4)
gspc2['day_lag5'] = gspc2['pct_change'].shift(5)
gspc2['day_lag6'] = gspc2['pct_change'].shift(6)
gspc2['day_lag7'] = gspc2['pct_change'].shift(7)
gspc2['day_lag8'] = gspc2['pct_change'].shift(8)
# gspc2['pct_change1'] = gspc2['Adj_Close'].shift(-1) / gspc2['Adj_Close']  - 1
# gspc2['pct_change2'] = gspc2['Adj_Close'].shift(-2) / gspc2['Adj_Close']  - 1
# gspc2['pct_change3'] = gspc2['Adj_Close'].shift(-3) / gspc2['Adj_Close']  - 1
# gspc2['pct_change4'] = gspc2['Adj_Close'].shift(-4) / gspc2['Adj_Close']  - 1
# gspc2['pct_change5'] = gspc2['Adj_Close'].shift(-5) / gspc2['Adj_Close']  - 1
# gspc2['pct_change6'] = gspc2['Adj_Close'].shift(-6) / gspc2['Adj_Close']  - 1
# gspc2['pct_change7'] = gspc2['Adj_Close'].shift(-7) / gspc2['Adj_Close']  - 1
# gspc2['pct_change8'] = gspc2['Adj_Close'].shift(-8) / gspc2['Adj_Close']  - 1

# gspc2 = gspc2.ix[(gspc2['pct_change'] > 0.0200)]
gspc2['lr3_10'], gspc2['lr3_10signal'], gspc2['hist'] = ta.MACDEXT(gspc2.Adj_Close.values, fastperiod=3, fastmatype=0, slowperiod=10, slowmatype=0, signalperiod=16, signalmatype=0)
gspc2['lr3_10_lag1'] = gspc2.lr3_10.shift(1)
gspc2['lr3_10_lag2'] = gspc2.lr3_10.shift(2)
gspc2['lr3_10_lag3'] = gspc2.lr3_10.shift(3)
gspc2['lr3_10_lag4'] = gspc2.lr3_10.shift(4)
gspc2['lr3_10_lag5'] = gspc2.lr3_10.shift(5)
gspc2['lr3_10signal_lag1'] = gspc2.lr3_10signal.shift(1)
gspc2['lr3_10signal_lag2'] = gspc2.lr3_10signal.shift(2)
gspc2['lr3_10signal_lag3'] = gspc2.lr3_10signal.shift(3)
gspc2['lr3_10signal_lag4'] = gspc2.lr3_10signal.shift(4)
gspc2['lr3_10signal_lag5'] = gspc2.lr3_10signal.shift(5)
gspc2['hist_lag1'] = gspc2['hist'].shift(1)
gspc2['hist_lag2'] = gspc2['hist'].shift(2)
gspc2['hist_lag3'] = gspc2['hist'].shift(3)
gspc2['hist_lag4'] = gspc2['hist'].shift(4)
gspc2['hist_lag5'] = gspc2['hist'].shift(5)
gspc2['rsi14'] = ta.RSI(gspc2.Adj_Close.values, timeperiod=14)
gspc2['rsi14_lag1'] = gspc2.rsi14.shift(1)
gspc2['rsi14_lag2'] = gspc2.rsi14.shift(2)
gspc2['rsi14_lag3'] = gspc2.rsi14.shift(3)
gspc2['rsi14_lag4'] = gspc2.rsi14.shift(4)
gspc2['rsi14_lag5'] = gspc2.rsi14.shift(5)
# gspc2['upperband'], gspc2['middleband'], gspc2['lowerband'] = ta.BBANDS(gspc2.Adj_Close.values, timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)
# # BB crossed down and up categorical labels
# gspc2.ix[(gspc2['Adj_Close'] <= gspc2['lowerband']) , 'crossed_down'] = 1
# gspc2.ix[(gspc2['Adj_Close'] > gspc2['lowerband']) , 'crossed_down'] = 0
# gspc2.ix[(gspc2['Adj_Close'] >= gspc2['upperband']) , 'crossed_up'] = 1
# gspc2.ix[(gspc2['Adj_Close'] < gspc2['upperband']) , 'crossed_up'] = 0
gspc2['mama'], gspc2['fama'] = ta.MAMA(gspc2.Adj_Close.values, fastlimit=0.5, slowlimit=0.05)
gspc2['hilbert'] = ta.HT_TRENDLINE(gspc2.Adj_Close.values)
gspc2['atr'] = ta.ATR(gspc2.High.values, gspc2.Low.values, gspc2.Close.values, timeperiod=14)
gspc2.ix[gspc2['pct_change'] >= 0, 'direction'] = 1
gspc2.ix[gspc2['pct_change'] < 0, 'direction'] = 0
gspc2['direction_lag1'] = gspc2['direction'].shift(1)
gspc2['direction_lag2'] = gspc2['direction'].shift(2)
gspc2['direction_lag3'] = gspc2['direction'].shift(3)
gspc2['direction_lag4'] = gspc2['direction'].shift(4)
gspc2['direction_lag5'] = gspc2['direction'].shift(5)
gspc2['direction_lag6'] = gspc2['direction'].shift(6)
gspc2['direction_lag7'] = gspc2['direction'].shift(7)
gspc2['direction_lag8'] = gspc2['direction'].shift(8)

# gspc2.ix[gspc2['pct_change2'] >= 0, 'pct_change2_yn'] = 1
# gspc2.ix[gspc2['pct_change2'] < 0, 'pct_change2_yn'] = 0
# gspc2.ix[gspc2['pct_change3'] >= 0, 'pct_change3_yn'] = 1
# gspc2.ix[gspc2['pct_change3'] < 0, 'pct_change3_yn'] = 0
# gspc2.ix[gspc2['pct_change4'] >= 0, 'pct_change4_yn'] = 1
# gspc2.ix[gspc2['pct_change4'] < 0, 'pct_change4_yn'] = 0
# gspc2.ix[gspc2['pct_change5'] >= 0, 'pct_change5_yn'] = 1
# gspc2.ix[gspc2['pct_change5'] < 0, 'pct_change5_yn'] = 0
# gspc2.ix[gspc2['pct_change6'] >= 0, 'pct_change6_yn'] = 1
# gspc2.ix[gspc2['pct_change6'] < 0, 'pct_change6_yn'] = 0
# gspc2.ix[gspc2['pct_change7'] >= 0, 'pct_change7_yn'] = 1
# gspc2.ix[gspc2['pct_change7'] < 0, 'pct_change7_yn'] = 0

gspc2.head(20)
gspc2.dropna(axis=0,inplace=True)
# gspc2[pd.isnull(gspc2).any(axis=1)]
gspc2['High_shift2'] = gspc2.High.shift(2)
gspc2['Low_shift2'] = gspc2.Low.shift(2)
gspc2['Close_shift2'] = gspc2.Close.shift(2)
gspc2['Open_dev_close_shift2'] = gspc2.Open / gspc2.Close_shift2
gspc2['High_dev_close_shift2'] = gspc2.Open / gspc2.High_shift2
gspc2['Low_dev_close_shift2'] = gspc2.Open / gspc2.Low_shift2
gspc2.dropna(axis=0,inplace=True)
gspc3 = gspc2[[ 'Open', 'Volume' , 'direction_lag1', 'direction_lag2','lr3_10_lag1', 'lr3_10_lag2', 'lr3_10_lag3', \
               'direction', 'High_shift2', 'Low_shift2', 'Close_shift2', 'Open_dev_close_shift2', \
               'High_dev_close_shift2',
       'Low_dev_close_shift2']]

In [361]:
gspc4 = round(gspc2.ix[:,['Adj_Close', 'pct_change', 'direction']],4)
gspc4.tail(10)
gspc4.shape


(1903, 3)

In [362]:
gspc4["pct_change"].values[:1408].shape, gspc4["pct_change"].values[1408:].shape

((1408,), (495,))

In [443]:
[2391.16, 2388.12, 2389.52, 2399.29, 2399.37]
scaler.fit_transform([2391.16, 2388.12, 2389.52, 2399.29, 2399.37])

p = np.reshape([-0.45955556, -1.        , -0.75111111,  0.98577778,  1.        ], (1, seq_length, 1))
p

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([[[-0.45955556],
        [-1.        ],
        [-0.75111111],
        [ 0.98577778],
        [ 1.        ]]])

In [374]:
seq_length = 5

dataX = []
dataY = []
for i in range(0, len(gspc4["pct_change"].values[293:1498]) - seq_length, 1):
    seq_in = gspc4["pct_change"].values[i:i + seq_length]
    scaler = MinMaxScaler(feature_range=(-1, 1))
    seq_in = scaler.fit_transform(seq_in)

    seq_out = gspc4["pct_change"].values[293:1498][i + seq_length]
    dataX.append([char for char in seq_in])
    dataY.append([seq_out])
    print(seq_in, '->', seq_out)
    
# test data
dataX_test = []
dataY_test = []
for i in range(0, len(gspc4["pct_change"].values[1498:]) - seq_length, 1):
    seq_in = gspc4["pct_change"].values[i:i + seq_length]
    scaler = MinMaxScaler(feature_range=(-1, 1))
    seq_in = scaler.fit_transform(seq_in)

    seq_out = gspc4["pct_change"].values[1498:][i + seq_length]
    dataX_test.append([char for char in seq_in])
    dataY_test.append([seq_out])
    print(seq_in, '->', seq_out)

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

[ 0.43169399 -0.91256831  1.         -0.70491803 -1.        ] -> 0.006
[-0.91794872  0.87692308 -0.72307692 -1.          1.        ] -> 0.0034
[ 0.89473684 -0.47368421 -0.71052632  1.         -1.        ] -> -0.0016
[-0.47368421 -0.71052632  1.         -1.         -0.95614035] -> 0.0006
[-0.71052632  1.         -1.         -0.95614035 -0.21929825] -> 0.0008
[ 1.         -0.51495017 -0.48172757  0.07641196 -1.        ] -> 0.001
[-0.65238095 -0.62857143 -0.22857143 -1.          1.        ] -> -0.0015
[-0.35177866 -0.01976285 -0.66007905  1.         -1.        ] -> -0.0002
[-0.01976285 -0.66007905  1.         -1.          0.36758893] -> 0.0113
[-0.66007905  1.         -1.          0.36758893  0.2055336 ] -> -0.0013
[ 1.         -1.          0.36758893  0.2055336   0.15019763] -> 0.005
[-1.          0.46300211  0.28964059  0.23044397  1.        ] -> -0.0021
[-0.3956044  -0.84615385 -1.          1.         -0.83516484] -> -0.0018
[-0.86792453 -1.          0.71698113 -0.85849057  1.        ]

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

-> -0.0074
[-1.         -0.43888889  1.         -0.21666667 -0.33888889] -> 0.0286
[-0.69281046  1.         -0.43137255 -0.5751634  -1.        ] -> -0.0106
[ 1.         -0.43137255 -0.5751634  -1.         -0.03921569] -> -0.0267
[ 0.23076923 -0.05128205 -0.88461538  1.         -1.        ] -> 0.007
[-0.05128205 -0.88461538  1.         -1.         -0.82051282] -> 0.0091
[ 0.33484163  1.          0.29411765  0.35746606 -1.        ] -> 0.0135
[ 1.          0.29411765  0.35746606 -1.          0.57466063] -> 0.0172
[ 0.42288557  0.49253731 -1.          0.73134328  1.        ] -> 0.0057
[ 0.49253731 -1.          0.73134328  1.         -0.2039801 ] -> -0.0098
[-1.          0.35672515  0.56725146 -0.37621832  1.        ] -> -0.0017
[ 0.06515581  0.37110482 -1.          1.          0.1898017 ] -> -0.0294
[ 0.37110482 -1.          1.          0.1898017   0.35977337] -> -0.0319
[-1.          1.          0.1898017   0.35977337 -0.33144476] -> 0.0061
[ 1.          0.02721088  0.23129252 -0.59863946

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

[-1.         -0.42857143 -0.55102041 -0.27891156  1.        ] -> -0.0043
[-0.84210526 -1.         -0.64912281  1.         -0.36842105] -> 0.0063
[-1.         -0.76608187  0.33333333 -0.57894737  1.        ] -> 0.0035
[-1.          0.24503311 -0.78807947  1.         -0.98675497] -> 0.0122
[ 0.24 -0.8   1.   -1.   -0.68] -> 0.0036
[-0.8         1.         -1.         -0.68       -0.65333333] -> -0.0028
[ 1.         -1.         -0.68       -0.65333333 -0.74666667] -> -0.023
[ 0.42857143  0.95604396  1.          0.84615385 -1.        ] -> 0.0143
[ 0.29927007  0.32846715  0.22627737 -1.          1.        ] -> -0.0143
[ 0.32846715  0.22627737 -1.          1.         -0.12408759] -> -0.0067
[ 0.22627737 -1.          1.         -0.12408759 -0.7810219 ] -> 0.0088
[-1.          0.53072626 -0.32960894 -0.83240223  1.        ] -> 0.0047
[ 0.48780488 -0.45121951 -1.          1.         -0.06097561] -> 0.0104
[-0.45121951 -1.          1.         -0.06097561 -0.25609756] -> 0.0
[-1.          1.     

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

[-1.    0.32  1.    0.84 -0.2 ] -> 0.0111
[-0.58064516 -0.03225806 -0.16129032 -1.          1.        ] -> -0.0003
[-0.03225806 -0.16129032 -1.          1.         -0.96774194] -> 0.0058
[ 0.4375    0.03125   1.        0.046875 -1.      ] -> 0.0048
[ 0.03125   1.        0.046875 -1.       -0.65625 ] -> 0.0012
[ 0.40659341 -0.26373626 -1.         -0.75824176  1.        ] -> -0.0065
[-0.26373626 -1.         -0.75824176  1.          0.95604396] -> 0.006
[-0.86666667 -0.64102564  1.          0.95897436 -1.        ] -> -0.0019
[-0.64102564  1.          0.95897436 -1.          0.34358974] -> 0.0062
[ 1.          0.96244131 -0.83098592  0.39906103 -1.        ] -> -0.0013
[ 1.         -0.8277512   0.42583732 -1.         -0.33014354] -> 0.0
[-0.75838926  1.         -1.         -0.06040268 -0.38255034] -> 0.0049
[ 1.         -1.         -0.06040268 -0.38255034  0.10067114] -> 0.0028
[-0.67346939  0.75510204  0.26530612  1.         -1.        ] -> -0.0074
[-0.38351254 -0.55555556 -0.29749104 -1. 

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

[-0.65979381  1.         -0.60824742 -1.          0.32989691] -> -0.0002
[ 0.13782991 -0.7771261  -1.         -0.24340176  1.        ] -> -0.0164
[-0.7771261  -1.         -0.24340176  1.          0.09090909] -> 0.0045
[-1.         -0.24340176  1.          0.09090909 -0.03812317] -> -0.0162
[-0.46712803  1.         -0.07266436 -0.22491349 -1.        ] -> -0.0063
[ 1.         -0.07266436 -0.22491349 -1.          0.44636678] -> -0.0085
[ 0.28229665  0.07177033 -1.          1.          0.32057416] -> 0.0204
[ 0.07177033 -1.          1.          0.32057416  0.30143541] -> 0.024
[-1.          1.          0.32057416  0.30143541 -0.31100478] -> 0.0046
[ 1.         -0.03649635 -0.06569343 -1.         -0.18248175] -> 0.0038
[ 1.          0.96491228 -0.15789474  0.8245614  -1.        ] -> 0.0017
[ 1.         -0.14285714  0.85714286 -1.          0.42857143] -> -0.0001
[-0.07692308  1.         -1.          0.53846154  0.75      ] -> 0.0033
[ 1.         -1.          0.53846154  0.75        0.1538461

[-0.36477987  0.55345912  1.         -1.         -0.28301887] -> -0.007
[ 0.55345912  1.         -1.         -0.28301887  0.83018868] -> -0.0046
[ 1.         -1.         -0.28301887  0.83018868  0.74213836] -> 0.0057
[-1.         -0.27388535  0.85350318  0.76433121  1.        ] -> 0.002
[-1.    0.77  0.63  1.    0.09] -> 0.0099
[ 0.49450549  0.18681319  1.         -1.         -0.47252747] -> -0.0053
[ 0.18681319  1.         -1.         -0.47252747 -0.40659341] -> 0.0061
[ 1.         -0.43307087 -0.05511811 -0.00787402 -1.        ] -> 0.0006
[ 0.14285714  0.9047619   1.         -1.          0.23809524] -> -0.0074
[ 0.95081967  1.         -0.03278689  0.60655738 -1.        ] -> -0.003
[ 1.         -0.03278689  0.60655738 -1.          0.85245902] -> -0.0004
[-0.08527132  0.51937984 -1.          0.75193798  1.        ] -> -0.0209
[ 0.51937984 -1.          0.75193798  1.          0.72093023] -> 0.0027
[-1.          0.75193798  1.          0.72093023  0.24031008] -> 0.0069
[ 0.47540984  1.  

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you

In [375]:
len(dataX), len(dataY), len(dataX_test), len(dataY_test)

(1200, 1200, 400, 400)

In [376]:
for i in range(1,len(dataX)):
    if len(dataX) % i == 0:
        if len(dataX_test) % i == 0:
            print(i)

1
2
4
5
8
10
16
20
25
40
50
80
100
200
400


In [472]:
X = np.reshape(dataX, (len(dataX), seq_length, 1))
len(dataY)

# dataY conveeted into binary classification 1.0 and 0.0
dataYseries = pd.DataFrame(dataY)
dataYseries.ix[dataYseries[0] >= 0, ] = 1
dataYseries.ix[dataYseries[0] < 0, ] = 0


# test data
X_test = np.reshape(dataX_test, (len(dataX_test), seq_length, 1))

dataYseries_test = pd.DataFrame(dataY_test)
dataYseries_test.ix[dataYseries[0] >= 0, ] = 1
dataYseries_test.ix[dataYseries[0] < 0, ] = 0

dataY[:10], y[:10] 

([[0.0060000000000000001],
  [0.0033999999999999998],
  [-0.0016000000000000001],
  [0.00059999999999999995],
  [0.00080000000000000004],
  [0.001],
  [-0.0015],
  [-0.00020000000000000001],
  [0.011299999999999999],
  [-0.0012999999999999999]],
 array([[ 0.,  1.],
        [ 0.,  1.],
        [ 1.,  0.],
        [ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 0.,  1.],
        [ 1.,  0.]]))

In [393]:
# moving dataYseries to on-hot-encoder
y = keras.utils.to_categorical(dataYseries)
y
# y test
y_test = keras.utils.to_categorical(dataYseries_test)
y_test.shape

(400, 2)

## Very important - data needs to be normalized in format [-1, 1] for LSTM
## After this change the results in training accuracy went drastically up

In [407]:
"""
stateful = False
"""
# create and fit the model
batch_size = 50
model = keras.models.Sequential()
model.add(keras.layers.LSTM(128, input_shape=(X.shape[1], X.shape[2])))
model.add(keras.layers.Dense(y.shape[1], activation='softmax'))
adam = keras.optimizers.Adam(lr=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
model.fit(X, y, epochs=600, batch_size=batch_size, verbose=1, shuffle=False)

scores = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)
# model.reset_states()
print("Model Accuracy: %.2f%%" % (scores[1]*100))


# seq_length = 4
# max accuracy = 0.5419 normalized 0 to 1 with all sorts of lr= [0.0001, 0.001, 0.01]
# max accuracy 0.5492 with normalized between -1 and 1, lr= 0.01
# neur = 3, epochs=200, bs = 1, norm [-1, 1], lr=0.05, acc 0.58
# neur = 3, epochs=200, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.58
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.59
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.04 --  acc = 0.584
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.06 --  acc = 0.5953
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.07 --  acc = 0.5953
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.08 --  acc = 0.5975
# neur = 3, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.1 --  acc = 0.5840
# neur = 16, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.747
# neur = 32, epochs=400, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.81
# neur = 64, epochs=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.85
# neur = 128, epochs=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.92
# seq = 5, neur = 128, epochs=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0

Epoch 1/600
1200/1200 [==============================] - 4s - loss: 0.7107 - acc: 0.5250     
Epoch 2/600
1200/1200 [==============================] - 0s - loss: 0.6914 - acc: 0.5242     
Epoch 3/600
1200/1200 [==============================] - 0s - loss: 0.6887 - acc: 0.5392     
Epoch 4/600
1200/1200 [==============================] - 0s - loss: 0.6888 - acc: 0.5500     
Epoch 5/600
1200/1200 [==============================] - 0s - loss: 0.6906 - acc: 0.5450     
Epoch 6/600
1200/1200 [==============================] - 0s - loss: 0.6914 - acc: 0.5433     
Epoch 7/600
1200/1200 [==============================] - 0s - loss: 0.6896 - acc: 0.5525     
Epoch 8/600
1200/1200 [==============================] - 0s - loss: 0.6905 - acc: 0.5500     
Epoch 9/600
1200/1200 [==============================] - 0s - loss: 0.6893 - acc: 0.5525     
Epoch 10/600
1200/1200 [==============================] - 0s - loss: 0.6896 - acc: 0.5467     
Epoch 11/600
1200/1200 [==============================] - 0

1200/1200 [==============================] - 0s - loss: 0.2880 - acc: 0.8825     
Epoch 88/600
1200/1200 [==============================] - 0s - loss: 0.2676 - acc: 0.8942     
Epoch 89/600
1200/1200 [==============================] - 0s - loss: 0.2553 - acc: 0.8933     
Epoch 90/600
1200/1200 [==============================] - 0s - loss: 0.2611 - acc: 0.8858     
Epoch 91/600
1200/1200 [==============================] - 0s - loss: 0.2652 - acc: 0.8842     
Epoch 92/600
1200/1200 [==============================] - 0s - loss: 0.2576 - acc: 0.8833     
Epoch 93/600
1200/1200 [==============================] - 0s - loss: 0.2751 - acc: 0.8858     
Epoch 94/600
1200/1200 [==============================] - 0s - loss: 0.2533 - acc: 0.8875     
Epoch 95/600
1200/1200 [==============================] - 0s - loss: 0.2949 - acc: 0.8733     
Epoch 96/600
1200/1200 [==============================] - 0s - loss: 0.2960 - acc: 0.8700     
Epoch 97/600
1200/1200 [==============================] - 0s - 

1200/1200 [==============================] - 0s - loss: 0.2424 - acc: 0.9167     
Epoch 173/600
1200/1200 [==============================] - 0s - loss: 0.3751 - acc: 0.8675     
Epoch 174/600
1200/1200 [==============================] - 0s - loss: 0.5366 - acc: 0.8125     
Epoch 175/600
1200/1200 [==============================] - 0s - loss: 0.5630 - acc: 0.7875     
Epoch 176/600
1200/1200 [==============================] - 0s - loss: 0.4783 - acc: 0.8058     
Epoch 177/600
1200/1200 [==============================] - 0s - loss: 0.4001 - acc: 0.8225     
Epoch 178/600
1200/1200 [==============================] - 0s - loss: 0.2734 - acc: 0.8817     
Epoch 179/600
1200/1200 [==============================] - 0s - loss: 0.2236 - acc: 0.9092     
Epoch 180/600
1200/1200 [==============================] - 0s - loss: 0.1631 - acc: 0.9392     
Epoch 181/600
1200/1200 [==============================] - 0s - loss: 0.1383 - acc: 0.9425     
Epoch 182/600
1200/1200 [=============================

1200/1200 [==============================] - 0s - loss: 0.0214 - acc: 0.9917     
Epoch 258/600
1200/1200 [==============================] - 0s - loss: 0.0213 - acc: 0.9917     
Epoch 259/600
1200/1200 [==============================] - 0s - loss: 0.0204 - acc: 0.9925     
Epoch 260/600
1200/1200 [==============================] - 0s - loss: 0.0207 - acc: 0.9917     
Epoch 261/600
1200/1200 [==============================] - 0s - loss: 0.0201 - acc: 0.9925     
Epoch 262/600
1200/1200 [==============================] - 0s - loss: 0.0196 - acc: 0.9933     
Epoch 263/600
1200/1200 [==============================] - 0s - loss: 0.0192 - acc: 0.9925     
Epoch 264/600
1200/1200 [==============================] - 0s - loss: 0.0201 - acc: 0.9925     
Epoch 265/600
1200/1200 [==============================] - 0s - loss: 0.0197 - acc: 0.9908     
Epoch 266/600
1200/1200 [==============================] - 0s - loss: 0.0192 - acc: 0.9917     
Epoch 267/600
1200/1200 [=============================

1200/1200 [==============================] - 0s - loss: 0.0508 - acc: 0.9858     
Epoch 343/600
1200/1200 [==============================] - 0s - loss: 0.0839 - acc: 0.9767     
Epoch 344/600
1200/1200 [==============================] - 0s - loss: 0.1289 - acc: 0.9500     
Epoch 345/600
1200/1200 [==============================] - 0s - loss: 0.1143 - acc: 0.9567     
Epoch 346/600
1200/1200 [==============================] - 0s - loss: 0.0968 - acc: 0.9583     
Epoch 347/600
1200/1200 [==============================] - 0s - loss: 0.0809 - acc: 0.9742     
Epoch 348/600
1200/1200 [==============================] - 0s - loss: 0.1027 - acc: 0.9675     
Epoch 349/600
1200/1200 [==============================] - 0s - loss: 0.2017 - acc: 0.9325     
Epoch 350/600
1200/1200 [==============================] - 0s - loss: 0.4007 - acc: 0.8650     
Epoch 351/600
1200/1200 [==============================] - 0s - loss: 0.4416 - acc: 0.8425     
Epoch 352/600
1200/1200 [=============================

1200/1200 [==============================] - 0s - loss: 0.0305 - acc: 0.9925     
Epoch 428/600
1200/1200 [==============================] - 0s - loss: 0.0312 - acc: 0.9892     
Epoch 429/600
1200/1200 [==============================] - 0s - loss: 0.0298 - acc: 0.9908     
Epoch 430/600
1200/1200 [==============================] - 0s - loss: 0.0326 - acc: 0.9883     
Epoch 431/600
1200/1200 [==============================] - 0s - loss: 0.0338 - acc: 0.9883     
Epoch 432/600
1200/1200 [==============================] - 0s - loss: 0.0448 - acc: 0.9817     
Epoch 433/600
1200/1200 [==============================] - 0s - loss: 0.0673 - acc: 0.9775     
Epoch 434/600
1200/1200 [==============================] - 0s - loss: 0.1161 - acc: 0.9675     
Epoch 435/600
1200/1200 [==============================] - 0s - loss: 0.1651 - acc: 0.9400     
Epoch 436/600
1200/1200 [==============================] - 0s - loss: 0.2662 - acc: 0.9192     
Epoch 437/600
1200/1200 [=============================

1200/1200 [==============================] - 0s - loss: 0.1231 - acc: 0.9467     
Epoch 513/600
1200/1200 [==============================] - 0s - loss: 0.1257 - acc: 0.9550     
Epoch 514/600
1200/1200 [==============================] - 0s - loss: 0.1059 - acc: 0.9642     
Epoch 515/600
1200/1200 [==============================] - 0s - loss: 0.0713 - acc: 0.9775     
Epoch 516/600
1200/1200 [==============================] - 0s - loss: 0.0745 - acc: 0.9783     
Epoch 517/600
1200/1200 [==============================] - 0s - loss: 0.0667 - acc: 0.9783     
Epoch 518/600
1200/1200 [==============================] - 0s - loss: 0.0590 - acc: 0.9833     
Epoch 519/600
1200/1200 [==============================] - 0s - loss: 0.0448 - acc: 0.9858     
Epoch 520/600
1200/1200 [==============================] - 0s - loss: 0.0425 - acc: 0.9850     
Epoch 521/600
1200/1200 [==============================] - 0s - loss: 0.0417 - acc: 0.9858     
Epoch 522/600
1200/1200 [=============================

1200/1200 [==============================] - 0s - loss: 0.1216 - acc: 0.9608     
Epoch 598/600
1200/1200 [==============================] - 0s - loss: 0.0934 - acc: 0.9650     
Epoch 599/600
1200/1200 [==============================] - 0s - loss: 0.0847 - acc: 0.9708     
Epoch 600/600
1200/1200 [==============================] - 0s - loss: 0.1184 - acc: 0.9675     
Model Accuracy: 53.75%


In [432]:
"""
stateful = True
"""
# create and fit the model
batch_size = 50
model = keras.models.Sequential()
model.add(keras.layers.LSTM(32, batch_input_shape=(batch_size, X.shape[1], X.shape[2]), stateful=True))
#model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dropout(0.4))
model.add(keras.layers.Dense(y.shape[1], activation='softmax'))
adam = keras.optimizers.Adam(lr=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
# rmsprop = keras.optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
for i in range(1000):
	model.fit(X, y, epochs=1, batch_size=batch_size, verbose=2, shuffle=False)
	model.reset_states()
# summarize performance of the model
scores = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)
# model.reset_states()
print("Model Accuracy: %.2f%%" % (scores[1]*100))

# the same accuracy as in stateful=False  = 0.5419 !! with input data being normalized between 0 and 1
# after changing it to be between -1 and 1 , accuracy went up to 0.5554
# after increasing lr from 0.01 to 0.05, accuracy = 0.73
# seq = 4, neur = 32, epo=300, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.856
# seq = 4, neur = 64, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.87
# seq = 4, neur = 128, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.946
# seq = 4, neur = 256, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.648
# seq = 4, neur = 128, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.616
# seq = 5, neur = 128, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0
# seq = 5, neur = 64, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0
# seq = 5, neur = 32, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 1.0
# seq = 5, neur = 16, epo=600, bs = X.shape[0], norm [-1, 1], lr=0.05 --  acc = 0.90
#seq = 5, neur = 32, dp=0.3, ep=1000, bs = 50, norm [-1, 1], lr=0.05 --  tr_acc = 0.64 tst_acc = 0.725
#seq = 5, neur = 32, dp=0.2, ep=1000, bs = 50, norm [-1, 1], lr=0.05 --  tr_acc = 0.706, tst_acc = 0.54
#seq = 5, neur = 32, dp=0.3, ep=1000, bs = 50, norm [-1, 1], lr=0.06 --  tr_acc = 0.615, tst_acc = 0.78
#seq = 5, neur = 32, dp=0.3, ep=1000, bs = 50, norm [-1, 1], lr=0.05 --  tr_acc = 0.6492, tst_acc = 0.6975
#seq = 5, neur = 32, dp=0.4, ep=1000, bs = 50, norm [-1, 1], lr=0.05 --  tr_acc = 0.6458, tst_acc = 0.74
#seq = 5, neur = 32, dp=0.4, ep=1000, bs = 50, norm [-1, 1], lr=0.06 --  tr_acc = 0.59, tst_acc = 0.85
# batch_norm, seq = 5, neur = 32, dp=0.4, ep=1000, bs = 50, norm [-1, 1], lr=0.05 --tr_acc = 0.54, tst_acc = 0.25
# batch_norm, seq = 5, neur = 32, dp=0.4, ep=1000, bs = 50, norm [-1, 1], lr=0.01 --tr_acc = 0.90, tst_acc = 0.56

Epoch 1/1
5s - loss: 0.7215 - acc: 0.5042
Epoch 1/1
0s - loss: 0.6925 - acc: 0.5392
Epoch 1/1
0s - loss: 0.6956 - acc: 0.5325
Epoch 1/1
0s - loss: 0.6943 - acc: 0.5333
Epoch 1/1
0s - loss: 0.6911 - acc: 0.5433
Epoch 1/1
0s - loss: 0.6917 - acc: 0.5508
Epoch 1/1
0s - loss: 0.6898 - acc: 0.5550
Epoch 1/1
0s - loss: 0.6906 - acc: 0.5508
Epoch 1/1
0s - loss: 0.6926 - acc: 0.5342
Epoch 1/1
0s - loss: 0.6904 - acc: 0.5508
Epoch 1/1
0s - loss: 0.6914 - acc: 0.5542
Epoch 1/1
0s - loss: 0.6902 - acc: 0.5475
Epoch 1/1
0s - loss: 0.6913 - acc: 0.5617
Epoch 1/1
0s - loss: 0.6890 - acc: 0.5500
Epoch 1/1
0s - loss: 0.6898 - acc: 0.5517
Epoch 1/1
0s - loss: 0.6900 - acc: 0.5475
Epoch 1/1
0s - loss: 0.6876 - acc: 0.5600
Epoch 1/1
0s - loss: 0.6876 - acc: 0.5492
Epoch 1/1
0s - loss: 0.6888 - acc: 0.5608
Epoch 1/1
0s - loss: 0.6917 - acc: 0.5508
Epoch 1/1
0s - loss: 0.6906 - acc: 0.5508
Epoch 1/1
0s - loss: 0.6891 - acc: 0.5483
Epoch 1/1
0s - loss: 0.6893 - acc: 0.5525
Epoch 1/1
0s - loss: 0.6836 - acc:

0s - loss: 0.6244 - acc: 0.6383
Epoch 1/1
0s - loss: 0.6342 - acc: 0.6258
Epoch 1/1
0s - loss: 0.6169 - acc: 0.6433
Epoch 1/1
0s - loss: 0.6221 - acc: 0.6417
Epoch 1/1
0s - loss: 0.6136 - acc: 0.6467
Epoch 1/1
0s - loss: 0.6158 - acc: 0.6483
Epoch 1/1
0s - loss: 0.6179 - acc: 0.6367
Epoch 1/1
0s - loss: 0.6208 - acc: 0.6308
Epoch 1/1
0s - loss: 0.6230 - acc: 0.6308
Epoch 1/1
0s - loss: 0.6079 - acc: 0.6375
Epoch 1/1
0s - loss: 0.6334 - acc: 0.6308
Epoch 1/1
0s - loss: 0.6213 - acc: 0.6542
Epoch 1/1
0s - loss: 0.6274 - acc: 0.6375
Epoch 1/1
0s - loss: 0.6328 - acc: 0.6375
Epoch 1/1
0s - loss: 0.6424 - acc: 0.6092
Epoch 1/1
0s - loss: 0.6391 - acc: 0.6175
Epoch 1/1
0s - loss: 0.6239 - acc: 0.6342
Epoch 1/1
0s - loss: 0.5816 - acc: 0.6675
Epoch 1/1
0s - loss: 0.6066 - acc: 0.6533
Epoch 1/1
0s - loss: 0.6066 - acc: 0.6575
Epoch 1/1
0s - loss: 0.6075 - acc: 0.6475
Epoch 1/1
0s - loss: 0.6234 - acc: 0.6367
Epoch 1/1
0s - loss: 0.6416 - acc: 0.6142
Epoch 1/1
0s - loss: 0.6200 - acc: 0.6342
Ep

0s - loss: 0.6314 - acc: 0.6308
Epoch 1/1
0s - loss: 0.6377 - acc: 0.6133
Epoch 1/1
0s - loss: 0.6365 - acc: 0.6250
Epoch 1/1
0s - loss: 0.6353 - acc: 0.6250
Epoch 1/1
0s - loss: 0.6425 - acc: 0.6267
Epoch 1/1
0s - loss: 0.6172 - acc: 0.6400
Epoch 1/1
0s - loss: 0.6246 - acc: 0.6517
Epoch 1/1
0s - loss: 0.6203 - acc: 0.6392
Epoch 1/1
0s - loss: 0.6273 - acc: 0.6258
Epoch 1/1
0s - loss: 0.6232 - acc: 0.6392
Epoch 1/1
0s - loss: 0.6382 - acc: 0.6175
Epoch 1/1
0s - loss: 0.6300 - acc: 0.6425
Epoch 1/1
0s - loss: 0.6148 - acc: 0.6358
Epoch 1/1
0s - loss: 0.6287 - acc: 0.6317
Epoch 1/1
0s - loss: 0.6193 - acc: 0.6400
Epoch 1/1
0s - loss: 0.6247 - acc: 0.6317
Epoch 1/1
0s - loss: 0.6397 - acc: 0.6175
Epoch 1/1
0s - loss: 0.6250 - acc: 0.6275
Epoch 1/1
0s - loss: 0.6574 - acc: 0.6258
Epoch 1/1
0s - loss: 0.6610 - acc: 0.5950
Epoch 1/1
0s - loss: 0.6388 - acc: 0.6158
Epoch 1/1
0s - loss: 0.6634 - acc: 0.6075
Epoch 1/1
0s - loss: 0.6418 - acc: 0.6083
Epoch 1/1
0s - loss: 0.6373 - acc: 0.6342
Ep

0s - loss: 0.6459 - acc: 0.6192
Epoch 1/1
0s - loss: 0.6576 - acc: 0.5892
Epoch 1/1
0s - loss: 0.6592 - acc: 0.5975
Epoch 1/1
0s - loss: 0.6463 - acc: 0.6100
Epoch 1/1
0s - loss: 0.6546 - acc: 0.6125
Epoch 1/1
0s - loss: 0.6594 - acc: 0.6258
Epoch 1/1
0s - loss: 0.6611 - acc: 0.5767
Epoch 1/1
0s - loss: 0.6577 - acc: 0.6033
Epoch 1/1
0s - loss: 0.6577 - acc: 0.6075
Epoch 1/1
0s - loss: 0.6516 - acc: 0.6275
Epoch 1/1
0s - loss: 0.6538 - acc: 0.6133
Epoch 1/1
0s - loss: 0.6611 - acc: 0.6033
Epoch 1/1
0s - loss: 0.6650 - acc: 0.5983
Epoch 1/1
0s - loss: 0.6553 - acc: 0.6075
Epoch 1/1
0s - loss: 0.6582 - acc: 0.5958
Epoch 1/1
0s - loss: 0.6647 - acc: 0.6092
Epoch 1/1
0s - loss: 0.6701 - acc: 0.5908
Epoch 1/1
0s - loss: 0.6720 - acc: 0.5667
Epoch 1/1
0s - loss: 0.6515 - acc: 0.6092
Epoch 1/1
0s - loss: 0.6555 - acc: 0.6092
Epoch 1/1
0s - loss: 0.6697 - acc: 0.5917
Epoch 1/1
0s - loss: 0.6586 - acc: 0.5950
Epoch 1/1
0s - loss: 0.6644 - acc: 0.5992
Epoch 1/1
0s - loss: 0.6564 - acc: 0.5925
Ep

0s - loss: 0.6424 - acc: 0.6275
Epoch 1/1
0s - loss: 0.6469 - acc: 0.6083
Epoch 1/1
0s - loss: 0.6585 - acc: 0.6058
Epoch 1/1
0s - loss: 0.6513 - acc: 0.6092
Epoch 1/1
0s - loss: 0.6443 - acc: 0.6042
Epoch 1/1
0s - loss: 0.6497 - acc: 0.5958
Epoch 1/1
0s - loss: 0.6624 - acc: 0.5842
Epoch 1/1
0s - loss: 0.6563 - acc: 0.6000
Epoch 1/1
0s - loss: 0.6514 - acc: 0.5983
Epoch 1/1
0s - loss: 0.6491 - acc: 0.6125
Epoch 1/1
0s - loss: 0.6571 - acc: 0.5992
Epoch 1/1
0s - loss: 0.6607 - acc: 0.5942
Epoch 1/1
0s - loss: 0.6547 - acc: 0.6017
Epoch 1/1
0s - loss: 0.6755 - acc: 0.5750
Epoch 1/1
0s - loss: 0.6638 - acc: 0.6075
Epoch 1/1
0s - loss: 0.6602 - acc: 0.6025
Epoch 1/1
0s - loss: 0.6538 - acc: 0.5958
Epoch 1/1
0s - loss: 0.6468 - acc: 0.5892
Epoch 1/1
0s - loss: 0.6542 - acc: 0.6000
Epoch 1/1
0s - loss: 0.6479 - acc: 0.6150
Epoch 1/1
0s - loss: 0.6575 - acc: 0.6125
Epoch 1/1
0s - loss: 0.6516 - acc: 0.6050
Epoch 1/1
0s - loss: 0.6393 - acc: 0.6217
Epoch 1/1
0s - loss: 0.6493 - acc: 0.6008
Ep

0s - loss: 0.6598 - acc: 0.5850
Epoch 1/1
0s - loss: 0.6604 - acc: 0.5833
Epoch 1/1
0s - loss: 0.6507 - acc: 0.5983
Epoch 1/1
0s - loss: 0.6588 - acc: 0.6025
Epoch 1/1
0s - loss: 0.6514 - acc: 0.6042
Epoch 1/1
0s - loss: 0.6597 - acc: 0.5992
Epoch 1/1
0s - loss: 0.6709 - acc: 0.5858
Epoch 1/1
0s - loss: 0.6685 - acc: 0.5775
Epoch 1/1
0s - loss: 0.6607 - acc: 0.5958
Epoch 1/1
0s - loss: 0.6831 - acc: 0.5850
Epoch 1/1
0s - loss: 0.6703 - acc: 0.5767
Epoch 1/1
0s - loss: 0.6629 - acc: 0.5850
Epoch 1/1
0s - loss: 0.6607 - acc: 0.5900
Epoch 1/1
0s - loss: 0.6696 - acc: 0.5850
Epoch 1/1
0s - loss: 0.6439 - acc: 0.6017
Epoch 1/1
0s - loss: 0.6643 - acc: 0.5908
Epoch 1/1
0s - loss: 0.6665 - acc: 0.5867
Epoch 1/1
0s - loss: 0.6609 - acc: 0.6058
 50/400 [==>...........................] - ETA: 29sModel Accuracy: 85.75%


In [521]:
model.predict_proba(X_test, batch_size=50, verbose=1)


 50/400 [==>...........................] - ETA: 0s

array([[ 0.43078133,  0.5692187 ],
       [ 0.46673501,  0.53326499],
       [ 0.47274294,  0.52725703],
       [ 0.41115975,  0.58884019],
       [ 0.45974681,  0.54025322],
       [ 0.48322594,  0.51677412],
       [ 0.42409962,  0.57590038],
       [ 0.38259801,  0.61740196],
       [ 0.32642409,  0.67357594],
       [ 0.39969996,  0.60030001],
       [ 0.36995968,  0.63004029],
       [ 0.15245643,  0.84754354],
       [ 0.46288037,  0.53711963],
       [ 0.51289344,  0.4871065 ],
       [ 0.26806661,  0.73193336],
       [ 0.40669411,  0.59330589],
       [ 0.43904957,  0.5609504 ],
       [ 0.40021431,  0.59978569],
       [ 0.40409261,  0.59590739],
       [ 0.40019003,  0.59980994],
       [ 0.25758865,  0.74241132],
       [ 0.50059378,  0.49940625],
       [ 0.40028918,  0.59971076],
       [ 0.37034026,  0.62965977],
       [ 0.40021792,  0.59978211],
       [ 0.3746148 ,  0.62538517],
       [ 0.33795312,  0.66204691],
       [ 0.41006947,  0.58993053],
       [ 0.40806651,

In [537]:
p = pd.read_csv("test.csv", header=None)
p = np.reshape(p.values, (50, seq_length))
for i in range(len(p)):
    p[i] = scaler.fit_transform(p[i])

p = np.reshape(p, (50, seq_length, 1))


model.predict(p, batch_size=50)
model.predict_classes(p, batch_size=50)
model.predict_on_batch(p)
model.predict_proba(p, batch_size=50)
for i in zip(model.predict_proba(p, batch_size=50), model.predict_classes(p, batch_size=50), model.predict(p, batch_size=50)):
    print("model.predict_proba", "--", i[0], "model.predict","--", i[2], "predict_classes", "--", i[1])



50/50 [==============================] - 0s
model.predict_proba -- [ 0.38373891  0.61626112] model.predict -- [ 0.38973126  0.61026871] predict_clases -- 1
model.predict_proba -- [ 0.36251354  0.63748646] model.predict -- [ 0.36251354  0.63748646] predict_clases -- 1
model.predict_proba -- [ 0.14950302  0.85049695] model.predict -- [ 0.14950302  0.85049695] predict_clases -- 1
model.predict_proba -- [ 0.40517813  0.59482187] model.predict -- [ 0.40517813  0.59482187] predict_clases -- 1
model.predict_proba -- [ 0.37012619  0.62987381] model.predict -- [ 0.37012619  0.62987381] predict_clases -- 1
model.predict_proba -- [ 0.92809069  0.07190929] model.predict -- [ 0.95142859  0.04857135] predict_clases -- 0
model.predict_proba -- [ 0.37223044  0.62776965] model.predict -- [ 0.36853829  0.63146174] predict_clases -- 1
model.predict_proba -- [ 0.1896919   0.81030804] model.predict -- [ 0.20518866  0.79481143] predict_clases -- 1
model.predict_proba -- [ 0.20383431  0.7961657 ] model.predi

/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/yol/miniconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape you